builds:
  - goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - 386

archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: amd64
    format_overrides:
      - goos: windows
        format: zip

brews:
  - description: Edit and create Kubernetes job from cronjob template using your EDITOR
    tap:
      owner: kitagry
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/kitagry/kj
    install: bin.install "kj"
