builds:
  - goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - 386

archives:
  - rlcp: true
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "freebsd" }}FreeBSD
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "386" }}32bit
      {{- else if eq .Arch "arm64" }}ARM64
      {{- else if eq .Arch "riscv64" }}RISCV
      {{- else }}{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ end }}

brews:
  - description: Edit and create Kubernetes job from cronjob template using your EDITOR
    tap:
      owner: kitagry
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/kitagry/kj
    install: bin.install "kj"
