name: Release

on:
  push:
    tags: ["*"]

jobs:
  release:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        cache: true

    - uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
